on:
  push:
    branches: [ testing-project-ISW2 ]
  pull_request:
    branches: [ testing-project-ISW2 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      # Assumi che il jar sia messo in una cartella "lib" nel repository
      - name: Install EvoSuite Standalone Runtime dependency
        run: mvn install:install-file \
               -Dfile=./lib/evosuite-standalone-runtime-1.2.0.jar \
               -DgroupId=org.evosuite \
               -DartifactId=evosuite-standalone-runtime \
               -Dversion=1.2.0 \
               -Dpackaging=jar \
               -DgeneratePom=true

      - name: Build and Test with Maven
        run: mvn -B clean install
